require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LeavesController do

  # This should return the minimal set of attributes required to create a valid
  # Leaf. As you add validations to Leaf, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {:name => 'alpha', :description => 'bleh', :type => 'Forum'}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LeavesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all leaves as @leaves" do
      leaf = Leaf.create! valid_attributes
      get :index, {}, valid_session
      assigns(:leaves).should eq([leaf.becomes(Forum)])
    end
  end

  describe "GET show" do
    it "assigns the requested leaf as @leaf" do
      leaf = Leaf.create! valid_attributes
      get :show, {:id => leaf.to_param}, valid_session
      assigns(:leaf).becomes(Leaf).should eq(leaf)
    end
  end

  describe "GET new" do
    it "assigns a new leaf as @leaf" do
      get :new, {}, valid_session
      assigns(:leaf).becomes(Leaf).should be_a_new(Leaf)
    end
  end

  describe "GET edit" do
    it "assigns the requested leaf as @leaf" do
      leaf = Leaf.create! valid_attributes
      get :edit, {:id => leaf.to_param}, valid_session
      assigns(:leaf).becomes(Leaf).should eq(leaf)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Leaf" do
        expect {
          post :create, {:leaf => valid_attributes}, valid_session
        }.to change(Leaf, :count).by(1)
      end

      it "assigns a newly created leaf as @leaf" do
        post :create, {:leaf => valid_attributes}, valid_session
        assigns(:leaf).should be_a(Leaf)
        assigns(:leaf).should be_persisted
      end

      it "redirects to the created leaf" do
        post :create, {:leaf => valid_attributes}, valid_session
        response.should redirect_to(Leaf.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved leaf as @leaf" do
        # Trigger the behavior that occurs when invalid params are submitted
        Leaf.any_instance.stub(:save).and_return(false)
        post :create, {:leaf => {}}, valid_session
        assigns(:leaf).should be_a_new(Leaf)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Leaf.any_instance.stub(:save).and_return(false)
        post :create, {:leaf => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested leaf" do
        leaf = Forum.create! valid_attributes
        Forum.any_instance.should_receive(:update_attributes).with({'name' => 'newname'})
        put :update, {:id => leaf.to_param, :leaf => {'name' => 'newname'}}, valid_session
      end

      it "assigns the requested leaf as @leaf" do
        leaf = Leaf.create! valid_attributes
        put :update, {:id => leaf.to_param, :leaf => valid_attributes}, valid_session
        assigns(:leaf).becomes(Leaf).should eq(leaf)
      end

      it "redirects to the leaf" do
        leaf = Leaf.create! valid_attributes
        put :update, {:id => leaf.to_param, :leaf => valid_attributes}, valid_session
        response.should redirect_to(leaf)
      end
    end

    describe "with invalid params" do
      it "assigns the leaf as @leaf" do
        leaf = Forum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Forum.any_instance.stub(:save).and_return(false)
        put :update, {:id => leaf.to_param, :leaf => {}}, valid_session
        assigns(:leaf).should eq(leaf)
      end

      it "re-renders the 'edit' template" do
        leaf = Forum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Forum.any_instance.stub(:save).and_return(false)
        # debugger
        put :update, {:id => leaf.to_param, :leaf => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested leaf" do
      leaf = Leaf.create! valid_attributes
      expect {
        delete :destroy, {:id => leaf.to_param}, valid_session
      }.to change(Leaf, :count).by(-1)
    end

    it "redirects to the leaves list" do
      leaf = Leaf.create! valid_attributes
      delete :destroy, {:id => leaf.to_param}, valid_session
      response.should redirect_to(leaves_url)
    end
  end

end
